name: Healthy Agency
favicon: null
layout_spectrum: 0.85211
typography_spectrum: 0.47513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a06292'
    - '#7ccae5'
    - '#fd868c'
    - '#4d85b2'
  brandStrength: 0.9811674181837589
  lightness: 0.625
  saturation: 0.25131718069314957
  rhythmicContrast: 0.5
purpose: []
