name: Healthy Agency
favicon: null
layout_spectrum: 0.5788019963074476
typography_spectrum: 0.8943383651785553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9811674181837589
  lightness: 0.47782511077821255
  saturation: 0.25131718069314957
  rhythmicContrast: 0.29143234621733427
purpose: []
